# Generated by Django 5.2.17 on 2026-09-14 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('focus_entity_type', models.CharField(blank=True, max_length=16)),
                ('focus_entity_id', models.UUIDField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_threads', to='accounts.membership')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=32)),
                ('mode', models.CharField(blank=True, max_length=16)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('flagged_input', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='assistant.conversation')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'membership', '-last_message_at'], name='asstconv_org_member_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['organization', 'conversation', 'position'], name='asstturn_conv_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationturn',
            constraint=models.UniqueConstraint(fields=('conversation', 'position'), name='uniq_assistant_turn_position'),
        ),
        enable_rls("assistant_conversation"),
        enable_rls("assistant_conversationturn"),
    ]
