# Generated by Django 5.2.17 on 2026-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('task_due', 'Task due'), ('meeting_soon', 'Meeting approaching'), ('call_soon', 'Call scheduled'), ('deal_assigned', 'Deal assigned to you'), ('deal_inactive', 'Deal inactivity warning'), ('customer_replied', 'Customer replied'), ('ai_high_risk', 'Deal at high risk'), ('integration_alert', 'Integration needs attention')], max_length=32),
        ),
    ]
