# Generated by Django 5.2.17 on 2026-09-12 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('own', 'own'), ('team', 'team'), ('all', 'all')], max_length=8)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='authz.role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='uniq_role_key_per_org', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission'),
        ),
    ]
