"""Audit action identifiers. Keep them stable: they are queried by admins and monitoring."""

AUTH_LOGIN = "auth.login"
AUTH_LOGIN_FAILED = "auth.login_failed"
AUTH_LOGOUT = "auth.logout"
AUTH_PASSWORD_CHANGED = "auth.password_changed"  # noqa: S105  # nosec B105 - action name, not a secret
AUTH_PASSWORD_RESET = "auth.password_reset"  # noqa: S105  # nosec B105 - action name, not a secret
AUTH_EMAIL_VERIFIED = "auth.email_verified"
AUTH_MFA_ENABLED = "auth.mfa_enabled"
AUTH_MFA_DISABLED = "auth.mfa_disabled"
AUTH_SESSIONS_REVOKED = "auth.sessions_revoked"
AUTH_SUSPICIOUS_LOGIN = "auth.suspicious_login"
AUTH_REAUTHENTICATED = "auth.reauthenticated"

ORG_CREATED = "org.created"
ORG_UPDATED = "org.updated"
ORG_SWITCHED = "org.switched"

MEMBER_INVITED = "members.invited"
MEMBER_INVITATION_REVOKED = "members.invitation_revoked"
MEMBER_JOINED = "members.joined"
MEMBER_ROLE_CHANGED = "members.role_changed"
MEMBER_DISABLED = "members.disabled"
MEMBER_ENABLED = "members.enabled"
MEMBER_SUSPENDED = "members.suspended"
MEMBER_REACTIVATED = "members.reactivated"
MEMBER_REMOVED = "members.removed"
MEMBER_TEAMS_CHANGED = "members.teams_changed"
MEMBER_INVITATION_RESENT = "members.invitation_resent"

TEAM_CREATED = "teams.created"
TEAM_UPDATED = "teams.updated"
TEAM_DELETED = "teams.deleted"
TEAM_MEMBER_ADDED = "teams.member_added"
TEAM_MEMBER_REMOVED = "teams.member_removed"

INTEGRATION_CONNECTED = "integrations.connected"
INTEGRATION_UPDATED = "integrations.updated"
INTEGRATION_DISCONNECTED = "integrations.disconnected"
INTEGRATION_DELETED = "integrations.deleted"
INTEGRATION_PAUSED = "integrations.paused"
INTEGRATION_RESUMED = "integrations.resumed"
INTEGRATION_CREDENTIALS_ROTATED = "integrations.credentials_rotated"  # nosec B105 - action name
INTEGRATION_OAUTH_STARTED = "integrations.oauth_started"
INTEGRATION_SHARING_CHANGED = "integrations.sharing_changed"
INTEGRATION_MAPPING_CHANGED = "integrations.mapping_changed"
INTEGRATION_INBOUND_ENABLED = "integrations.inbound_enabled"
INTEGRATION_INBOUND_SECRET_ROTATED = "integrations.inbound_secret_rotated"  # noqa: S105  # nosec B105
INTEGRATION_SYNC_STARTED = "integrations.sync_started"
INTEGRATION_SYNC_COMPLETED = "integrations.sync_completed"
INTEGRATION_SYNC_FAILED = "integrations.sync_failed"
INTEGRATION_CONFLICT_RESOLVED = "integrations.conflict_resolved"
WEBHOOK_CREATED = "webhooks.created"
WEBHOOK_UPDATED = "webhooks.updated"
WEBHOOK_DELETED = "webhooks.deleted"
WEBHOOK_SECRET_ROTATED = "webhooks.secret_rotated"  # noqa: S105  # nosec B105 - action name
WEBHOOK_REJECTED = "webhooks.inbound_rejected"
API_CREDENTIAL_CREATED = "api_credentials.created"
API_CREDENTIAL_REVOKED = "api_credentials.revoked"

TENANT_MISMATCH_ATTEMPT = "tenant.mismatch_attempt"
SYSTEM_ACCESS = "system.unscoped_access"
