# Generated by Django 5.2.17 on 2026-09-13 01:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rls'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'last_name', 'first_name'], name='contact_org_name_idx'), models.Index(fields=['organization', 'email'], name='contact_org_email_idx'), models.Index(fields=['organization', 'company'], name='contact_org_company_idx'), models.Index(fields=['organization', 'owner'], name='contact_org_owner_idx'), models.Index(fields=['organization', '-created_at'], name='contact_org_created_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='contact_search_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('first_name', ''), _negated=True), models.Q(('last_name', ''), _negated=True), models.Q(('email', ''), _negated=True), _connector='OR'), name='contact_has_identity')],
            },
        ),
    ]
