# Generated by Django 5.2.17 on 2026-09-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation_details_member_status'),
        ('importexport', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='checkpoint_row',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'updated_at'], name='importjob_status_updated_idx'),
        ),
    ]
