# Generated by Django 5.2.17 on 2026-09-17 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rls'),
        ('teams', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invitation',
            name='send_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled')], default='active', max_length=16),
        ),
        # Until now "disabled" meant a reversible suspension (members.disable / members.enable). Keep that
        # meaning under its new name; "disabled" is from here on reserved for members removed from the
        # organization. RLS is forced on the table, so the rewrite runs with the transaction-local system flag.
        migrations.RunSQL(
            "SELECT set_config('app.system', 'on', true);"
            " UPDATE accounts_membership SET status = 'suspended' WHERE status = 'disabled';",
            reverse_sql=(
                "SELECT set_config('app.system', 'on', true);"
                " UPDATE accounts_membership SET status = 'disabled' WHERE status = 'suspended';"
            ),
        ),
    ]
