# Generated by Django 5.2.17 on 2026-09-13 01:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=160)),
                ('website', models.CharField(blank=True, max_length=2048)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('company_size', models.CharField(blank=True, max_length=16)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('revenue_currency', models.CharField(blank=True, max_length=3)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'name'], name='company_org_name_idx'), models.Index(fields=['organization', 'owner'], name='company_org_owner_idx'), models.Index(fields=['organization', '-created_at'], name='company_org_created_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='company_search_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('annual_revenue__gte', 0), ('annual_revenue__isnull', True), _connector='OR'), name='company_revenue_nonneg')],
            },
        ),
    ]
