# Generated by Django 5.2.17 on 2026-09-13 01:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('entity_type', models.CharField(choices=[('contact', 'Contact'), ('company', 'Company'), ('deal', 'Deal'), ('product', 'Product')], max_length=16)),
                ('key', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{0,39}$')])),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('integer', 'Whole number'), ('number', 'Decimal number'), ('currency', 'Currency amount'), ('percent', 'Percent'), ('date', 'Date'), ('datetime', 'Date and time'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('multi_select', 'Multi-select'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL')], max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['organization', 'entity_type', 'position'], name='customfield_org_entity_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'entity_type', 'key'), name='uniq_customfield_key'), models.CheckConstraint(condition=models.Q(('key__regex', '^[a-z][a-z0-9_]{0,39}$')), name='customfield_key_format')],
            },
        ),
    ]
