# Generated by Django 5.2.17 on 2026-09-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
