# Generated by Django 5.2.17 on 2026-09-13 10:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.core.rls import enable_rls
from apps.core.search import search_vector_trigger


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rls'),
        ('companies', '0003_lifecycle_activity'),
        ('contacts', '0003_lifecycle_activity'),
        ('deals', '0006_probability_overridden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('task', 'Task'), ('call', 'Call'), ('meeting', 'Meeting')], max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=8)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_url', models.CharField(blank=True, max_length=2048)),
                ('direction', models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=8)),
                ('outcome', models.CharField(blank=True, choices=[('connected', 'Connected'), ('no_answer', 'No answer'), ('voicemail', 'Voicemail'), ('busy', 'Busy'), ('interested', 'Interested'), ('not_interested', 'Not interested'), ('follow_up_required', 'Follow-up required')], max_length=24)),
                ('reminder_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='companies.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='deals.deal')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='activities.activity')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.membership')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', 'owner', 'status', 'start_at'], name='activity_org_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', 'kind', 'start_at'], name='activity_org_kind_start_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', 'start_at'], name='activity_org_start_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', 'deal'], name='activity_org_deal_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', 'contact'], name='activity_org_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', 'company'], name='activity_org_company_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', 'reminder_at'], name='activity_org_reminder_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['organization', '-created_at'], name='activity_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='activity_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__isnull', True), ('start_at__isnull', True), ('end_at__gte', models.F('start_at')), _connector='OR'), name='activity_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('status', 'completed'), _negated=True), _connector='OR'), name='activity_completed_at_consistent'),
        ),
        migrations.AddIndex(
            model_name='activityattendee',
            index=models.Index(fields=['organization', 'membership'], name='attendee_org_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityattendee',
            constraint=models.UniqueConstraint(fields=('activity', 'membership'), name='uniq_activity_attendee'),
        ),
        enable_rls("activities_activity"),
        enable_rls("activities_activityattendee"),
        search_vector_trigger("activities_activity", {"A": ["title"], "C": ["description", "location"]}),
    ]
