# Generated by Django 5.2.17 on 2026-09-13 01:51

import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rls'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_label', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_at', models.DateTimeField()),
                ('duration_in_previous_stage', models.DurationField(blank=True, null=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('import', 'Import'), ('ai_confirmed', 'AI (confirmed)'), ('automation', 'Automation')], default='user', max_length=16)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18)),
                ('amount_base', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('probability', models.PositiveSmallIntegerField(default=10)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=255)),
                ('stage_entered_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('next_activity_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
            ],
        ),
    ]
