# Generated by Django 5.2.17 on 2026-09-13 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rls'),
        ('contacts', '0001_initial'),
        ('deals', '0001_initial'),
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='pipelines.pipeline'),
        ),
        migrations.AddField(
            model_name='deal',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_deals', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='pipelines.pipelinestage'),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='dealcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_links', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='dealcontact',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_contacts', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='dealcontact',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='dealproduct',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='dealproduct',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
    ]
