# Generated by Django 5.2.17 on 2026-09-13 01:51

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rls'),
        ('deals', '0002_initial'),
        ('pipelines', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_lines', to='products.product'),
        ),
        migrations.AddField(
            model_name='dealstagehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='dealstagehistory',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='dealstagehistory',
            name='from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pipelines.pipelinestage'),
        ),
        migrations.AddField(
            model_name='dealstagehistory',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='dealstagehistory',
            name='to_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipelines.pipelinestage'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'pipeline', 'stage'], name='deal_org_pipeline_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'status', 'expected_close_date'], name='deal_org_status_close_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'owner', 'status'], name='deal_org_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'company'], name='deal_org_company_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', '-created_at'], name='deal_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='deal_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('probability__lte', 100)), name='deal_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='deal_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='deal_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('status', 'open')), ('closed_at__isnull', False), _connector='OR'), name='deal_closed_at_consistent'),
        ),
        migrations.AddConstraint(
            model_name='dealcontact',
            constraint=models.UniqueConstraint(fields=('deal', 'contact'), name='uniq_deal_contact'),
        ),
        migrations.AddConstraint(
            model_name='dealproduct',
            constraint=models.UniqueConstraint(fields=('deal', 'product'), name='uniq_deal_product'),
        ),
        migrations.AddConstraint(
            model_name='dealproduct',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='dealproduct_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='dealproduct',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='dealproduct_discount_range'),
        ),
        migrations.AddIndex(
            model_name='dealstagehistory',
            index=models.Index(fields=['deal', 'changed_at'], name='dealhistory_deal_changed_idx'),
        ),
    ]
