# Generated by Django 5.2.17 on 2026-09-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rls'),
        ('companies', '0002_rls_search'),
        ('contacts', '0002_rls_search'),
        ('deals', '0004_rls_triggers'),
        ('pipelines', '0002_rls'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'stage', '-stage_entered_at'], name='deal_org_stage_entered_idx'),
        ),
    ]
