# Generated by Django 5.2.17 on 2026-09-14 09:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension

from apps.core.rls import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_rls'),
    ]

    operations = [
        # `vector` is not a trusted extension, so a superuser installs it once per database
        # (infra/postgres/init/02-extensions.sql in dev, infra/postgres/prod-roles.sql in
        # production). This is then a no-op that keeps the migration self-describing.
        VectorExtension(),
        migrations.CreateModel(
            name='IndexEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('note', 'Note'), ('email', 'Email'), ('whatsapp', 'WhatsApp message'), ('activity', 'Meeting or call'), ('deal', 'Deal description')], max_length=16)),
                ('source_id', models.UUIDField()),
                ('operation', models.CharField(choices=[('upsert', 'Index or re-index'), ('delete', 'Remove from the index')], default='upsert', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed'), ('stale', 'Stale')], default='pending', max_length=12)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('chunk_count', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status', 'available_at'], name='ragevent_org_status_idx'), models.Index(fields=['status', 'available_at'], name='ragevent_status_avail_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_type', 'source_id'), name='uniq_rag_index_event_source')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('note', 'Note'), ('email', 'Email'), ('whatsapp', 'WhatsApp message'), ('activity', 'Meeting or call'), ('deal', 'Deal description')], max_length=16)),
                ('source_id', models.UUIDField()),
                ('chunk_index', models.PositiveSmallIntegerField(default=0)),
                ('entity_type', models.CharField(blank=True, max_length=16)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('source_version', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=64)),
                ('embedding_version', models.PositiveSmallIntegerField(default=1)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('entity_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('source_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membership')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'source_type', 'source_id'], name='ragchunk_org_source_idx'), models.Index(fields=['organization', 'entity_type', 'entity_id'], name='ragchunk_org_entity_idx'), models.Index(fields=['organization', 'entity_owner'], name='ragchunk_org_entowner_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='ragchunk_search_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='ragchunk_embedding_idx', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('organization', 'source_type', 'source_id', 'chunk_index'), name='uniq_rag_chunk_identity')],
            },
        ),
        # Same tenant boundary as every other CRM table: retrieved text is CRM data.
        enable_rls("rag_indexevent"),
        enable_rls("rag_knowledgechunk"),
    ]
